config/routes.rb
Rails.application.routes.draw do

  get 'organisations/index'

  resources :profiles

  resources :animals

  devise_for :organisations

  root 'welcome#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. 
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities

    user ||= Organisation.new # guest user (not logged in)

    # General READ permission
    can :read, :all

    # A profile can only be edited/updated by the organisation it belongs to    
    can :edit, Profile, organisation_id: user.id
    can :update, Profile, organisation_id: user.id

    # An animal can only be edited/updated/deleted by the organisation it belongs to    
    can :edit, Animal, organisation_id: user.id
    can :update, Animal, organisation_id: user.id
    can :destroy, Animal, organisation_id: user.id
  end
end

app/models/animal.rb
class Animal < ActiveRecord::Base

  # Should always belong to an organisation
  validates_presence_of :organisation
  belongs_to :organisation
  # Should always have a name
  validates_presence_of :name
  # Should always have a sex
  validates_presence_of :sex
  # Should always have a birth date
  validates_presence_of :birthdate
  # Should always have a description
  validates_presence_of :description

  # Sex should be either 'male' or 'female'
  validates :sex, inclusion: { in: %w(male female) }
end

app/models/organisation.rb
class Organisation < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable
  
  # Organisations can register animals         
  has_many :animals, dependent: :destroy

  # Organisations have a profile
  has_one :profile, dependent: :destroy

  # Auto generate profile on creation
  after_create :build_profile

  # Scopes for querying
  scope :including_profile, -> { includes(:profile) }

  private ###################################################################

  def build_profile
  	profile = Profile.new 
  	profile.organisation = self
  	profile.save
  end
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :organisation

  validates_presence_of :organisation

  has_attached_file :logo, 
    storage: :s3,
    s3_credentials: "#{Rails.root}/config/aws.yml",
    path: ":class/:attachment/:id/:style",
    url: ':s3_domain_url',
    styles: { 
      :original => ['400x400>', :png],
      :thumbnail => ['', :png]
    },
    convert_options: { 
      :original => "-strip",
      :thumbnail => "-thumbnail 80x80^ -gravity center -extent 80x80"
    }

  # Validate content type
  validates_attachment_content_type :logo, :content_type => /\Aimage/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController  
  before_action :set_animal, only: [:show, :edit, :update, :destroy]

  # GET /animals
  # GET /animals.json
  def index
    @animals = Animal.all
  end

  # GET /animals/1
  # GET /animals/1.json
  def show
  end

  # GET /animals/new
  def new
    @animal = Animal.new
  end

  # GET /animals/1/edit
  def edit
    authorize! :edit, @animal
  end

  # POST /animals
  # POST /animals.json
  def create        
    @animal = Animal.new(animal_params)
    @animal.organisation = current_organisation

    if @animal.save
      redirect_to @animal, notice: 'Animal was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /animals/1
  # PATCH/PUT /animals/1.json
  def update
    authorize! :update, @animal
    if @animal.update(animal_params)
      redirect_to @animal, notice: 'Animal was successfully updated.' 
    else
      render :edit 
    end
  end

  # DELETE /animals/1
  # DELETE /animals/1.json
  def destroy
    authorize! :destroy, @animal
    @animal.destroy
    redirect_to animals_url, notice: 'Animal was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_animal
      @animal = Animal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def animal_params
      params.require(:animal).permit(:name, :sex, :birthdate, :description)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # Redefine CanCan defaults
  def current_ability
    @current_ability ||= Ability.new(current_organisation)
  end

  # Dealing with unauthorised accesses
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end
end

app/controllers/organisations_controller.rb
class OrganisationsController < ApplicationController
  def index
  	@organisations = Organisation.including_profile.order('profiles.name ASC')
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  # CanCan will automatically load and authorise the profile (RESTFul style)
  load_and_authorize_resource

  def initialize
    super
    s3 = AWS::S3.new
    @s3_bucket = s3.buckets[AWS_CONFIG['bucket']]
  end

  def update
    # If a logo was attached
    if logo_update?
      update_logo
      # (update.js.erb should be rendered)
    elsif @profile.update(profile_params)
      # Redirect finally
      redirect_to @profile, notice: 'Profile was successfully updated.'
    else
      render :edit
    end
  end

  private ############################################################################

  # Never trust parameters from the scary internet, only allow the white list through.
  def profile_params
    params.require(:profile).permit(:name,
                                    :organisation_id,
                                    :description)
  end

  # Move S3 object
  def copy_and_delete(raw_source, paperclip_file_path)
    destination = @s3_bucket.objects[paperclip_file_path]
    sub_source = CGI.unescape(raw_source)
    # The file_path ends up adding an extra "/" in the beginning. We remove this.
    sub_source.slice!(0)
    source = @s3_bucket.objects["#{sub_source}"]
    # copy_to is a method originating from the aws-sdk gem
    source.copy_to(destination)
    # delete temp file
    source.delete
  end

  def logo_update?
    params[:filename]
  end

  def update_logo
      # This is where paperclip expects the original picture
      paperclip_file_path = "profiles/logos/#{@profile.id}/original"
      # This is where it actually is right now (temporal location)
      pic_source = params[:filepath]
      # Now copy from temp location to where paperclip expects it to be
      copy_and_delete pic_source, paperclip_file_path
      # Grab info from s3
      upload_head = @s3_bucket.objects[paperclip_file_path].head
      @profile.logo_file_name     = params[:filename]
      @profile.logo_file_path     = paperclip_file_path
      @profile.logo_file_size     = upload_head.content_length
      @profile.logo_content_type  = upload_head.content_type
      @profile.logo_updated_at    = upload_head.last_modified
      # Reprocess to generate styles      
      @profile.save
      @profile.logo.reprocess!      
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index		
	end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	
end

app/helpers/organisations_helper.rb
module OrganisationsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/animals/_form.html.haml
= form_for @animal do |f|
  - if @animal.errors.any?
    #error_explanation
      %h2= "#{pluralize(@animal.errors.count, "error")} prohibited this animal from being saved:"
      %ul
        - @animal.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :sex
    = f.text_field :sex
  .field
    = f.label :birthdate
    = f.date_select :birthdate
  .field
    = f.label :description
    = f.text_area :description
  .actions
    = f.submit 'Save'

app/views/animals/edit.html.haml
%h1 Editing animal

= render 'form'

= link_to 'Show', @animal
\|
= link_to 'Back', animals_path

app/views/animals/index.html.haml
%h1 Listing animals

%table
  %tr
    %th Name
    %th Sex
    %th Birthdate
    %th Organisation
    %th Description
    %th
    %th

  - @animals.each do |animal|
    %tr
      %td= link_to animal.name, animal
      %td= animal.sex
      %td= animal.birthdate
      %td= animal.organisation.email
      %td= animal.description

%br

app/views/animals/new.html.haml
%h1 New animal

= render 'form'

= link_to 'Back', animals_path

app/views/animals/show.html.haml
%p
  %b Name:
  = @animal.name
%p
  %b Sex:
  = @animal.sex
%p
  %b Birthdate:
  = @animal.birthdate
%p
  %b Organisation:
  = @animal.organisation.email
%p
  %b Description:
  = @animal.description

- if can? :edit, @animal
  = link_to 'Edit', edit_animal_path(@animal), id: 'edit-animal-link'
  = button_to 'Delete', animal_path(@animal), id: 'delete-animal-button', method: :delete
= link_to 'Back', animals_path

app/views/confirmable/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/_flash_messages.html.haml
- flash.each do | name, msg |
  %p{ class: "flash-#{name}" }
    = msg
    %button.close
      &times;

app/views/layouts/_footer.html.haml
PetRescue.eu
%address
  #author
    (c) Author Name
  #message
    Leave a message?
    = link_to 'info@petrescue.eu', 'mailto:info@petrescue.eu' , id: 'email'

app/views/layouts/_navigation_bar.html.haml
#navigation-header
  %button.navbar-toggle{'data-toggle'.to_sym => 'collapse', 'data-target'.to_sym => '#collapsible-navigation-bar'}
    .icon-bar
    .icon-bar
    .icon-bar
  = link_to 'PetRescue.eu', root_path, id: 'home-link'

#collapsible-navigation-bar.collapse.navbar-collapse
  / Page navigation links
  %ul#navigation
    %li= link_to "List of animals", animals_path, :id => 'animals-list-link'
    %li= link_to "List of organisations", organisations_index_path, :id => 'organisations-list-link'
    - if organisation_signed_in?
      %li= link_to 'Register Animal', new_animal_path, :id => 'animal-registration-link'
  
  / Authentication and Account management links
  %ul#identity-management
    - if organisation_signed_in?
      %li.dropdown
        %a.dropdown-toggle{href: '#', 'data-toogle'.to_sym => 'dropdown'}
          .glyphicon.glyphicon-cog
          My Organisation
          .caret        
        %ul.dropdown-menu
          %li= link_to 'Edit profile', edit_profile_path(current_organisation.profile), id: 'edit-profile-link'
          %li= link_to 'Manage account', edit_organisation_registration_path(current_organisation), id: 'manage-account-link'
          %li= link_to "Logout", destroy_organisation_session_path, method: :delete, id: 'logout-link'
    - else
      %p
        Are you an Organisation? 
      %li= link_to "Sign up", new_organisation_registration_path, :id => 'signup-link'
      %li= link_to "Login", new_organisation_session_path, :id => 'login-link'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title PetRescue
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %meta{name: 'viewport', content: 'width=device-width, initial-scale=1'}
  %body
    %nav#main-nav
      = render 'layouts/navigation_bar'
    %section#flashes
      = render 'layouts/flash_messages'
    %main
      = yield
    %footer
      = render 'layouts/footer'

app/views/organisations/index.html.haml
%header List of organisations

#organisations-list
  - @organisations.each do |organisation|
    %ul
      #logo= image_tag organisation.profile.logo.url(:thumbnail)
      %li#name= link_to organisation.profile.name, profile_path(organisation.profile)
      %li#email= link_to organisation.email, "mailto:#{organisation.email}" 
%br

app/views/profiles/_upload.html.haml
= s3_uploader_form 	callback_url: "#{profile_path(@profile)}",
          callback_method: "PATCH",
          max_file_size: 5.megabytes,
          acl: 'private',
					id: "s3-uploader" do
  = file_field_tag :file, multiple: false

%script#template-upload{type: "text/x-tmpl"}
  .upload{id: 'file-{%=o.unique_id%}'}
    {%=o.name%}
    .progress
      .bar{style: "width: 0%"}

#uploads
  %header
    Uploading...
  #progress-meters

app/views/profiles/edit.html.haml
%header Editing profile

= image_tag @profile.logo.url(:thumbnail), id: 'logo-edit'

= form_for @profile do |f|
  - if @profile.errors.any?
    #error_explanation
      %h2= "#{pluralize(@profile.errors.count, "error")} prohibited this profile from being saved:"
      %ul
        - @profile.errors.full_messages.each do |msg|
          %li= msg
          
  .field
    = f.label :name
    = f.text_field :name  
  .field
    = f.label :description
    = f.text_area :description
  .actions
    = f.submit 'Save'

= render 'upload'

= link_to 'Back', root_path

app/views/profiles/show.html.haml
= image_tag @profile.logo.url
= image_tag @profile.logo.url(:thumbnail)
%h1= @profile.name

%p
  %b Email:
  = @profile.organisation.email
%p
  %b Description:
  = @profile.description

- if organisation_signed_in?
  = link_to 'Edit', edit_profile_path(@profile)
  \|
= link_to 'Back', root_path

app/views/profiles/update.js.erb
// Update logo picture shown
$('#logo-edit').attr("src", '<%= @profile.logo.url(:thumbnail) %>')
// Close modal
$('#uploads').modal('hide');
// Clear progress bars in case the modal is shown again
$('#progress-meters').html('');

app/views/welcome/index.html.haml
%article#welcome
  %header
    %h1
      Welcome to PetRescue.eu
    %p
      Non-profit project helping animals in shelters across Europe to find a home
    
    = link_to 'Adopt a Pet', animals_path, id: 'adopt-link'
    = link_to 'Register your shelter', new_organisation_registration_path, id: 'register-link'
      
  %p#purpose
    Lots of animals in need.
    Organisations make a great effort but the task is difficult.
    Lots of good people becoming aware of the problem.
    
    PetRescue.eu is a personal non-profit project aiming to serve as a networking tool for
    animal-welfare organisations and potential adoptive homes across Europe, thus helping
    animals to find the homes they need and a better life.
    
    In order to attain the mentioned goal, we put a series of services at the disposal
    of both animal organisations and individuals with the aim of putting them in contact
    whenever an opportunity for adoption or collaboration arises.

  %section#tools_for_individuals
    %header What can I do here as an individual ?
    %p In PetRescue.eu, we provide tools so that individuals can:
    %ul
      %li
        Look for animals in need for a home in our database, which spans the whole Europe
      %p
        It is not always easy to find the proper pet since each home can have different
        needs or preferences about the characteristics of their ideal pet. A better
        match between a home and a pet helps towards a succesful adoption and happier
        life for both. Broadening the scope of the search to the whole Europe certainly
        increases the possibilities of finding the perfect home for each pet, and vice
        versa.
        PetRescue.eu aims to provide such capability by supporting organisations across
        all Europe in registering their animals with our data base.
        Individuals who find a pet that they think fits their needs will be able to contact the 
        organisation that registered the pet to communicate their interest in the adoption, which 
        will be managed by the organisation itself under its own terms.
      %li
        Get to know animal-welfare organisations
      %p
        There are always people interested in collaborating, volunteering, making
        donations or somehow providing help to organisations, but can have some
        requirements too (for example finding a nearby organisation, one that focus on
        animals with special needs, particular breeds, or other reasons).
        PetRescue aims to provide information of interest about organisations so that
        they can be easily found and contacted, supporting people willing to help in
        their search for organisations to support.
        With this regard, for each of the organisations registered in the platform
        there is information including an overview of their goals and principles, location, scope 
        of their work, a list of news, and a list of the animals they have currently registered 
        as well as animals they have succesfully found a home for.
      %li
        Learn ways to support animal-welfare organisations in their job
      %p
        There are some informative sections in this web site in which interested
        people can learn ways of helping organisations to keep protecting animals
        lives. See X, X, and X.

  %section#tools_for_organisations
    %header What can I do here as an organisation ?
    %p In PetRescue.eu, we provide tools so that organisations can:
    %ul
      %li
        Find adoptions for their pets
      %p
        As stated before, the main goal of PetRescue.eu project is to help rescued
        animals to find the homes they need.
        Organisations which sign up are be able to register their animals in the
        platform so that every interested individual can browse them and see if any of
        them matches their needs. In that case, that individual could contact the organisation to 
        state their interest, and the adoption would be managed by the own organisation under its 
        own terms, dealing directly with the individual.
      %li
        Get known
      %p
        The PetRescue.eu project aims to serve as a platform to promote the work of animal-
        welfare organisations.
        Organisations which sign up are be able to publish information about their
        purpose, their principles, their history, their work, their needs, and any
        other relevant information. They can also publish news so that everyone is
        updated with their current status.
      %li
        Promote their principles
      %p
        By clearly stating their principles and the main motivation behind them on
        their profiles, organisations are effectively using this platform as a means
        for the promotion of these principles over a target audience that spans the
        whole Europe.
      %li
        Get support
      %p
        Promotion of the organisations work and principles will also increase the
        probabilities of finding support from people that feel they want to
        collaborate with them.
        A general informative section on ways to help is provided in the web site,
        and also any organisation can ask for particular help through their published
        news.